name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install apache2
          sudo apt install -y lsb-release gnupg2 ca-certificates apt-transport-https software-properties-common
          sudo add-apt-repository ppa:ondrej/php
          sudo apt-get install libapache2-mod-php
          sudo apt-get install php8.1
          sudo apt-get install php8.1-xml
          sudo apt-get install php8.1-mbstring
          sudo apt-get install php8.1-zip
          sudo apt-get install php8.1-mysql
          composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev


      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 13.211.159.191
          username: ubuntu
          key: ${{ secrets.unique1 }}
          port: 22
          script: |
            cd /var/www/html
            sudo git clone https://github.com/GUFTUGUWITHASIF/gittthubaction.git
            cd gittthubaction
                    
            sudo omposer update --no-interaction --prefer-dist --optimize-autoloader
            sudo composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
            sudo chown -R www-data:www-data storage/
            sudo chmod -R 755 storage/
            sudo chown -R www-data:www-data bootstrap/cache/
            sudo chmod -R 755 bootstrap/cache/
            php artisan migrate --force

